### ISSUE TITLE
Laboratory Work#0

### ISSUE THREAD

**Issue by OlkaLyubomska** [oleksandrblazhko/ai182-lyubomska#1]

**Comment by OlkaLyubomska** [comment]
Hello world1

**Comment by OlkaLyubomska** [comment]
Я вибачаюсь, та я припустилася помилки, коли називала лабораторні роботи на
гіті, тому це була тільки 0 робота, першу я зроблю на вихідних)

пт, 14 жовт. 2022 р. о 19:49 Oleksandr Blazhko ***@***.***>
пише:

**Comment by oleksandrblazhko** [comment]
Так, це була нульова робота.
Назвіть наступну роботу 01.

**Comment by OlkaLyubomska** [comment]
Добре, дякую

пт, 14 жовт. 2022, 7:58 пп користувач Oleksandr Blazhko <
***@***.***> пише:
